### ISSUE TITLE
Support for multi languages sites

### ISSUE THREAD

**Issue by JS-Media-Creation** [TecArt/grav-plugin-tecart-cookie-manager#17]
Hey there, love using this plugin. But I would appreciate the support for multi languages sites.

**Comment by ChristianaHoJo** [comment]
Hi @Schw3pps,
thank you for your positive feedback. Unfortunately, we currently have no capacity to develop it further. Volunteers are welcome. :-)

**Comment by Schw3pps** [comment]
@ChristianaHoJo Would love to help, but my knowledge is not sufficient for this :(

**Comment by pmoreno-rodriguez** [comment]
Hi @ChristianaHoJo, take a look at this [pull request](https://github.com/TecArt/grav-plugin-tecart-cookie-manager/pull/18). The translation I have made is for Spanish, but I have modified the blueprints.yaml file to support multiple languages. Translation into other languages should be done by more volunteers.

**Comment by 01Kuzma** [comment]
Hello!
Is it possible to translate the front-end information with `languages.yaml` in the themes folder?
I've tried something like this with secondary language:
```
ru:
  SITE:
    TITLE: .ru    
    AUTHOR:
      COPYRIGHT: ''
  DESCRIPTION: ''
  MENU: Меню
    ...
  PLUGINS:
    PLUGIN_TECART_COOKIE_MANAGER:
      BUTTON_ACCEPT_TEXT_DEFAULT: Принять
      BANNER_TITLE: 'Используем cookie'
```

But the text is not changing. It still displays the language strings which are entered in the backed of the plugin.
